site_name: ROS Tutorials for YonseiDrone
site_description: This is a ROS tutorial for beginners written in Korean.
nav:
  - Home: index.md
  - 'Introduction': 01_Introduction/1_introduction.md
  - 'ROS Noetic 기초':
    - '간단한 Publisher, Subscriber 노드 작성하기': 02_ros_noetic_basic/1_simple_pub_sub_node.md
    - '메세지에 대한 이해와 커스텀 메세지 다루기': 02_ros_noetic_basic/2_custom_msg.md
    - 'roslaunch로 여러 노드 실행하기': 02_ros_noetic_basic/3_roslaunch.md
  - 'Turtlesim':
    - 'turtlesim 실행하고 키보드로 조작하기': ./03_turtlesim/1_turtlesim_teleop.md
  - 'Gazebo'
  - 'MAVROS'
theme:
  name: material
  language: ko
  font:
    text: Nanum Gothic
    code: Roboto Mono
  logo: assets/book-solid.svg
  favicon: assets/yonseidroneicon.png
  extra:
    homepage: https://yonseidrone.com
  features:
    - content.code.copy
    - content.code.select
    - navigation.top
  palette:
    scheme: slate
    primary: orange
    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default 
    #   primary: orange
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: orange
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
extra:
  social:
    - icon: material/storefront-edit-outline
      link: https://yonseidrone.com
    - icon: fontawesome/brands/github
      link: https://github.com/YonseiDrone
copyright: Copyright &copy; 2023 Chanjoon Park
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
      toc_depth: 0
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - admonition

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css